# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Hello-World' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'OpenTok', '2.22.2'

  # Pods for Hello-World

  target 'Hello-WorldTests' do
    inherit! :search_paths
    pod 'OpenTok', '2.22.2'
  end

end
