# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Hello-World' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hello-World

  target 'Hello-WorldTests' do
    inherit! :search_paths
    pod 'OpenTok', '= 2.12.0'
  end

end
