# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'Hello-World' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'OTXCFramework', '2.31.1'

  # Pods for Hello-World

  target 'Hello-WorldTests' do
    inherit! :search_paths
    pod 'OTXCFramework', '2.31.1'
  end

end
